### ISSUE TITLE
Downloads.curl(::String) or @to_request "..."

### ISSUE THREAD

**Issue by anandijain** [JuliaLang/Downloads.jl#105]
I posted in #helpdesk but might be better seen here.

I think it'd be useful to have a way to give Downloads a string that you'd normally give the shell.
Ie `Downloads.curl("curl -X GET \"https://reactome.org/ContentService/data/pathway/R-HSA-5673001/containedEvents\" -H "accept: application/json" -o .data.json")`

It'd be nice to not have to reorganize all the options and flags myself. Additionally a macro like `@to_request` to build the Downloads.request expr for me would be super useful.

**Comment by anandijain** [comment]
Yeah, I sort of agree that I could just run(`curl`) but there is also something to be said for wanting pure julia, even if Downloads is basically just calling run lower down. 

I might have some time later to throw the macro together. I don't think it'd be that difficult.

**Comment by fredrikekre** [comment]
This is not `curl` so it is, IMO, a bit strange to add `curl` syntax on top of the Downloads.jl API. In particular since you can already do
```
using LibCURL_jll

curl() do curl
    run(`$curl --version`)
end
```
with less depencendies and not having to implement anything.

**Comment by StefanKarpinski** [comment]
> even if Downloads is basically just calling run lower down.

It isn't, it uses the `libcurl` library directly. This is already closed so saying so may be beating a dead horse, but it would be quite a lot of work to emulate the `curl` command feature-for-feature, bug-for-bug.
