### ISSUE TITLE
Curl.SYSTEM_SSL compares Curl.SSL_VERSION against a typo

### ISSUE THREAD

**Issue by daniellivingston** [JuliaLang/Downloads.jl#109]
The parameter [`Curl.SYSTEM_SSL`](https://github.com/JuliaLang/Downloads.jl/blob/master/src/Curl/Curl.jl#L44) will always evaluate to `false` on macOS.

It is defined as:

```julia
const SYSTEM_SSL =
    Sys.isapple() && startswith(SSL_VERSION, "SecureTranspart") ||
    Sys.iswindows() && startswith(SSL_VERSION, "Schannel")
```

Note that macOS compares against `"SecureTranspart"`, when `Curl.SSL_VERSION == "SecureTransport"` (`transpArt` vs. `transpOrt`).

Is this intentional?

### Minimal Reproducible Example

```julia
julia> versioninfo()
Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)

shell> pwd
/Users/livingston/playground/tmp/curl_issue/Downloads.jl/src

julia> using Base.Experimental: @sync

julia> using NetworkOptions; using ArgTools; include("Curl/Curl.jl"); using .Curl

julia> Curl.SYSTEM_SSL
false

julia> Sys.isapple()
true

julia> startswith(Curl.SSL_VERSION, "SecureTranspart")
false

julia> Curl.SSL_VERSION
"SecureTransport"
```

**Comment by StefanKarpinski** [comment]
Oh yeah, that would do it.

**Comment by StefanKarpinski** [comment]
Wow, there's even a test of this that has a perfectly matching one-character bug that makes it pass:

https://github.com/JuliaLang/Downloads.jl/blob/4b56bd2385124c0c47772a16b0897dfac4f92831/test/runtests.jl#L8

🤦🏻‍♂️🤦🏻‍♂️
