### ISSUE TITLE
not clear from readme how to actually use headers kwarg

### ISSUE THREAD

**Issue by anandijain** [JuliaLang/Downloads.jl#119]
an example is definitely needed, one with AbstractVec and one with Dict

**Comment by anandijain** [comment]
```julia
HEADER = "Authorization: Bearer $TOKEN"
URL = "..."
cmd = `curl -H $HEADER $URL`
run(cmd)
Downloads.download(URL; headers=[HEADER])
```
MWE. I don't see what's wrong but getting 404 for the `download` but getting json just fine with the normal curl

**Comment by anandijain** [comment]
ahh i think the wording is just unclear for: "If the headers keyword argument is provided, it must be a vector or dictionary whose elements are all pairs of strings."

Pairs of strings is for both accepted types. 

It still was not obvious from the tests or the readme that the correct way to do this is:
HEADER = `"Authorization" => "Bearer $TOKEN"`

**Comment by StefanKarpinski** [comment]
Want to make a PR to add this to the docs?

**Comment by StefanKarpinski** [comment]
The documentation does say:

> If the `headers` keyword argument is provided, it must be a vector or dictionary whose elements are all pairs of strings.

That is only stated in the docstring for `download` and the `request` docstring references that. What do you think would help clarify this?
