### ISSUE TITLE
is it too much to ask to move the helper functions in test/setup.jl into the module?

### ISSUE THREAD

**Issue by anandijain** [JuliaLang/Downloads.jl#120]
specifically, it was kind of odd to see the response body get thrown away. I can see why you might not want the body as part of the Response struct, but to then not provide a download_json and request_json seems weird.

I can see this issue getting closed, since its so easy for someone to write themselves

**Comment by anandijain** [comment]
example, before I saw test/ I wrote this trash myself 

```julia 
out = IOBuffer()
r = Downloads.request(URL; headers=[HEADER], output = out)
s = String(take!(out))
js = JSON3.read(s)
```
which doesn't easily generalize to a function because of kwarg handling

```
https://github.com/JuliaLang/Downloads.jl/blob/master/test/setup.jl#L11-L32 is written much cleaner.

**Comment by StefanKarpinski** [comment]
Yes, it's too much to ask. We don't want to add a real JSON parser as a dependency of this package — the tests use the [smallest, most half-assed possible JSON parser imaginable](https://github.com/JuliaLang/Downloads.jl/blob/master/test/json.jl). If we exposed parsing request results as JSON as a real API we would have to use a real JSON parser, which would make one of the JSON packages a dependency of Downloads. That would be undesirable if this were a normal package, but it's a stdlib, which would make it sooo much worse: it would force whatever JSON parser we depend on to be a stdlib also, which would tie it to the Julia version and prevent people from installing any other version.

**Comment by anandijain** [comment]
makes sense, thanks
