### ISSUE TITLE
Feature request: customize the value of `CURLOPT_MAXREDIRS` on a per-call basis

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/Downloads.jl#173]
It looks like `CURLOPT_MAXREDIRS` is currently hard-coded to `50`:

https://github.com/JuliaLang/Downloads.jl/blob/43899e71eed709866f96dd624f1c369a1c8e26a3/src/Curl/Easy.jl#L51-L51

This makes sense, since `50` is also the default for the command-line `curl`.

However, it would be nice if users could customize the value of `CURLOPT_MAXREDIRS` on a per-call basis. By "per-call basis", I mean that users could do something like this:

```julia
julia> resp_1 = request(url_1; maxredirs = 25)

julia> resp_2 = request(url_2; maxredirs = 100)
```

In this example, the value of `maxredirs` passed as a kwarg to the `request` function will only affect that individual call.

**Comment by StefanKarpinski** [comment]
Why would you need to change it?

**Comment by StefanKarpinski** [comment]
At a higher level, we could expose every single option that libcurl has. I don't want to do that, which is why it's possible to add an `easy_hook` to directly set arbitrary curl options.

**Comment by DilumAluthge** [comment]
> which is why it's possible to add an `easy_hook` to directly set arbitrary curl options

That's probably what I should do. Do you have any example code for this?

**Comment by DilumAluthge** [comment]
From looking at the test suite, I'm guessing it'll be something like this:

```julia
import Downloads

easy_hook = (easy, info) -> begin
    timeout_seconds = 120
    timeout_milliseconds = round(Clong, timeout_seconds * 1_000)
    Downloads.Curl.setopt(easy, Downloads.Curl.CURLOPT_TIMEOUT_MS, timeout_milliseconds)
end
downloader = Downloads.Downloader()
downloader.easy_hook = easy_hook

output_tempfile = Downloads.download("https://julialang.org/"; downloader = downloader)
output_contents = read(output_tempfile, String)
```

**Comment by DilumAluthge** [comment]
I think that the ability to provide a custom `easy_hook`is exactly what I was looking for.
