### ISSUE TITLE
[Ques] trying to download a private Git repo

### ISSUE THREAD

**Issue by AbhimanyuAryan** [JuliaLang/Downloads.jl#174]
Trying to download private Github repo using any idea how can I achieve that? How can I pass `username` and Github `access token` to approve this?

```
julia> download("https://github.com/AbhimanyuAryan/craftware/archive/refs/heads/master.zip", "master.zip")
ERROR: HTTP/1.1 404 Not Found while requesting https://github.com/AbhimanyuAryan/craftware/archive/refs/heads/master.zip
Stacktrace:
  [1] (::Downloads.var"#3#4"{Nothing, Vector{Pair{String, String}}, Float64, Nothing, Bool, Nothing, String})(output::IOStream)
    @ Downloads /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Downloads.jl:233
  [2] open(f::Downloads.var"#3#4"{Nothing, Vector{Pair{String, String}}, Float64, Nothing, Bool, Nothing, String}, args::String; kwargs::Base.Iterators.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:write,), Tuple{Bool}}})
    @ Base ./io.jl:330
  [3] arg_write(f::Function, arg::String)
    @ ArgTools /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/ArgTools/src/ArgTools.jl:86
  [4] #download#2
    @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Downloads.jl:221 [inlined]
  [5] download(url::String, output::String)
    @ Downloads /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Downloads.jl:221
  [6] #invokelatest#2
    @ ./essentials.jl:708 [inlined]
  [7] invokelatest
    @ ./essentials.jl:706 [inlined]
  [8] do_download
    @ ./download.jl:33 [inlined]
  [9] download(url::String, path::String)
    @ Base ./download.jl:28
 [10] top-level scope
    @ REPL[3]:1
```

**Comment by AbhimanyuAryan** [comment]
following https://stackoverflow.com/questions/18126559/how-can-i-download-a-single-raw-file-from-a-private-github-repo-using-the-comman

gives me: 

```
download("""https://github.com/AbhimanyuAryan/craftware/archive/refs/heads/master.zip?login="abhimanyuaryan"&token="xxx"""", "master.zip")
ERROR: syntax: cannot juxtapose string literal
```

**Comment by DilumAluthge** [comment]
I would recommend that you do either of the following:

1. Clone the repo over Git[^1] and then check out the desired branch.
2. Use the `Download a repository archive (tar)`[^2] GitHub API. To authenticate to the GitHub API, you'll need to pass your token in a header. If you use Downloads.jl to make the API calls, you'll pass your headers in the `headers` keyword argument.

[^1]: `git clone https://x-access-token:$(GITHUB_TOKEN)@$github.com/foo/bar.git`
[^2]: https://docs.github.com/en/rest/reference/repos#download-a-repository-archive-tar
[^3]: The name of the header will be `Authorization`, and the contents of the header will be `token $(GITHUB_TOKEN)`.
[^4]: https://docs.github.com/en/rest/overview/resources-in-the-rest-api#oauth2-token-sent-in-a-header

**Comment by DilumAluthge** [comment]
Also, please ask follow-up questions on Julia Discourse: https://discourse.julialang.org/

**Comment by AbhimanyuAryan** [comment]
thanks @DilumAluthge
