### ISSUE TITLE
Add `maxlog` to `@error` messages?

### ISSUE THREAD

**Issue by ericphanson** [JuliaLang/Downloads.jl#189]
I just had a CI run take 1hr 20 minutes instead of 30, and the logs didn't show. I got GHA to let me download them, and found a 4 GB file with
```julia
┌ Error: curl_multi_socket_action: 8
└ @ Downloads.Curl /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/Downloads/src/Curl/utils.jl:36
```
repeated 14 million times. This was disappointing to me because the PR the CI failed on was adding a lock around some data loading to avoid the Downloads multithreading bugs on 1.7, but also that's an incredible number of error messages.

What about adding `maxlog=10_000` or something? If it's really high, then it probably won't be ever dropping useful messages, and it can avoid this pathological scenario. And of course one can just use a logger that doesn't respect `maxlog` to get them, if needed.

**Comment by DilumAluthge** [comment]
Makes sense to me!

**Comment by ericphanson** [comment]
Thanks @DilumAluthge!
