### ISSUE TITLE
current version does not match available version or Julia version

### ISSUE THREAD

**Issue by lmiq** [JuliaLang/Downloads.jl#238]
Since this package is one shipped in the Julia image, shouldn't it provide versions with the same number as the Julia versions, as other packages? 

In parallel, here current stable version is 1.5.3, but in Julia 1.10 it seems that 1.6.0 is shipped. I'm confused about that, while trying to test some package with downgraded versions.

**Comment by giordano** [comment]
This is the case for _many_ stdlibs.

**Comment by lmiq** [comment]
That the version necessary in the [compat]  entry does not match any version available in the site? How can one know than what to add to the compat entry?

**Comment by lmiq** [comment]
Well, just leave it, I'm confused about some stdlibs having true versions, others not, and now a little bit more by those that do have true versions may not match the actual package versions.

**Comment by giordano** [comment]
To be clear, I think it'd be better to have proper version numbering for this package ([last change](https://github.com/JuliaLang/Downloads.jl/commit/43899e71eed709866f96dd624f1c369a1c8e26a3) was three years ago), but it doesn't necessarily have to follow julia's version number.

**Comment by DilumAluthge** [comment]
> Yeah, I got a bit lazy about making releases; it's annoying to keep up, especially with backports to LTS, which makes the release sequence non-linear.

Ideally we would have tooling to automate most of the release process for external stdlibs. Especially as we start moving more and more stdlibs out to their own repos.
