### ISSUE TITLE
Nightly Build failing, it says Downloads.jl does not include NetworkOptions.jl but it does.

### ISSUE THREAD

**Issue by drizk1** [JuliaLang/Downloads.jl#246]
Hello.  Thank you for your work on this package.

I am trying to add Oracle via Oracle.jl as a backend for TidierDB. For the tests, I keep getting the [error](https://github.com/TidierOrg/TidierDB.jl/pull/28) below for the nightly build. I have tried deleting and rebuilding the manifest.toml with no success and the same error.  

```
ERROR: LoadError: ArgumentError: Package Downloads does not have NetworkOptions in its dependencies:
- Note that the following manifests in the load path were resolved a potentially
  different DEV version of the current version, which may be the cause
  of the error:
    /tmp/jl_7bpMQ5/Manifest.toml
```

If this issue is not something I should raise here, I will close this issue. Thank you.

**Comment by drizk1** [comment]
My apologies, thank you for your timely response. 

I have just recommitted the [manifest.toml](https://github.com/TidierOrg/TidierDB.jl/blob/add_oracle_support/Manifest.toml) here. 

I am not sure how to add a minimal reproducer since I am not actually using the package but this is rather due to dependencies in other packages ( i think)

**Comment by giordano** [comment]
https://github.com/TidierOrg/TidierDB.jl/blob/0a1e5e68602b780b945b2f7c69f16191232b4399/Manifest.toml#L3 that's a manifest for julia v1.9.1, manifest files are expected not to be necessarily compatible across different julia versions.

**Comment by drizk1** [comment]
Hmm ok. So is there no way for this test to be able to pass for the nightly build as well?

**Comment by giordano** [comment]
> Hmm ok. So is there no way for this test to be able to pass for the nightly build as well?

Normally I'd say it shouldn't be a problem, but I don't know what you're doing to run into that issue, and without a minimal reproducer to look at it's hard to do or say anything more specific.

**Comment by drizk1** [comment]
Ok, thank you for you help. I wish I knew what I was doing to run into this issue to. If i figure out how to come up with a minimal reproducer I will return to this issue. For now I will leave it in a branch outside of main. Thank you!

**Comment by NLaws** [comment]
I'm [seeing the same message](https://github.com/JuliaRegistries/General/actions/runs/11566676274/job/32195736504?pr=118265#step:17:702)
```sh
ERROR: LoadError: ArgumentError: Package Downloads does not have NetworkOptions in its dependencies:
- You may have a partially installed environment. Try `Pkg.instantiate()`
  to ensure all packages in the environment are installed.
- Or, if you have Downloads checked out for development and have
  added NetworkOptions as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with Downloads
```
from the Julia package Registry AutoMerge. The package CommonOPF builds fine locally, but I'm using Julia v1.10 and the AutoMerge task is using Julia 1.11. The issue might lie in [OpenDSSDirect.jl](https://github.com/dss-extensions/OpenDSSDirect.jl/blob/master/Project.toml) because above the LoadError for Downloads [the AutoMerge log states](https://github.com/JuliaRegistries/General/actions/runs/11566676274/job/32195736504?pr=118265#step:17:401):
```sh
ERROR: Error building `OpenDSSDirect`:
```
Maybe this is reproducible via what the AutoMerge task is doing?
