### ISSUE TITLE
Mechanism to gracefully interrupt an ongoing `Downloads.request`

### ISSUE THREAD

**Issue by tanmaykm** [JuliaLang/Downloads.jl#255]
We often have APIs that stream results over a period of time. What would be a reliable way to interrupt such an ongoing `Downloads.request`?

From what I gather, interrupting the julia task is not ideal. So I think this has to be done using libcurl APIs. And probably `Downloads.request` needs to provide a mechanism to signal an interruption to it somehow. Putting up this issue for discussion and resolution.

**Comment by tanmaykm** [comment]
Seems like [curl_multi_remove_handle](https://curl.se/libcurl/c/curl_multi_remove_handle.html) may be a way to interrupt an easy handle gracefully. The caller could probably pass an optional `Base.Event` to `Downloads.request` if it wants to interrupt it?

**Comment by vtjnash** [comment]
Sounds like a likely api from curl. The common way to handle it would be having downloads return a state object that you can interact with (ask progress, wait on, pause, close, etc) either as a different function or using the kwarg wait=false

**Comment by tanmaykm** [comment]
I have put up https://github.com/JuliaLang/Downloads.jl/pull/256 with an implementation of what we discussed here.

I felt that returning a state object from `request` method would be a significantly larger change, both in terms of code and also because it will change the API. For now this PR adds a single kwarg to allow cancelling. The async implementation can be a larger future PR.

**Comment by tanmaykm** [comment]
Fixed by #256 and #259
