### ISSUE TITLE
Downloading files with FTP protocol fails with `Could not resolve host`

### ISSUE THREAD

**Issue by giordano** [JuliaLang/Downloads.jl#36]
Julia v1.5:
```
julia> download("ftp://xmlsoft.org/libxslt/libxslt-1.1.33.tar.gz")
"/tmp/jl_PhxwJQ"
```

with `Downloads`:
```
julia> Downloads.download("ftp://xmlsoft.org/libxslt/libxslt-1.1.33.tar.gz")
ERROR: Could not resolve host: 
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] (::Downloads.var"#2#3"{Vector{Pair{String, String}}, Downloads.Downloader, String})(io::IOStream)
   @ Downloads ~/repo/julia/usr/share/julia/stdlib/v1.6/Downloads/src/Downloads.jl:69
 [3] arg_write(f::Downloads.var"#2#3"{Vector{Pair{String, String}}, Downloads.Downloader, String}, arg::Nothing)
   @ ArgTools ~/repo/julia/usr/share/julia/stdlib/v1.6/ArgTools/src/ArgTools.jl:101
 [4] #download#1
   @ ~/repo/julia/usr/share/julia/stdlib/v1.6/Downloads/src/Downloads.jl:49 [inlined]
 [5] download
   @ ~/repo/julia/usr/share/julia/stdlib/v1.6/Downloads/src/Downloads.jl:48 [inlined]
 [6] top-level scope
   @ REPL[8]:1
```

**Comment by StefanKarpinski** [comment]
Reopening since this still doesn't work on Linux.

**Comment by StefanKarpinski** [comment]
I got stuck on https://github.com/JuliaLang/Downloads.jl/pull/45. There's something broken in `libcurl`'s `ftp_state_pasv_resp` function and I have no idea what's going on in there. `curl` works fine, but I can't figure out how `curl` is configured differently. If someone can debug that function or figure out how `curl` is configured differently then progress can be made on this issue.

**Comment by StefanKarpinski** [comment]
Also note that it's _only_ a problem on Linux: on macOS and Windows the FTP download succeeds. It's possible that this is a transient libcurl bug that's hidden by some option that gets set in the `curl` tool, which, as I understand it, is the primary way that the library gets tested.

**Comment by KlausC** [comment]
I just found out, that the problem disappears, if we don't use the `TCP_FASTOPEN` option.

Do `Downloads/Curl/Easy.jl: 47`
`    curl_easy_setopt(easy.handle, CURLOPT_TCP_FASTOPEN, false) # failure ok, unsupported`
should work around the upstream issue.
