### ISSUE TITLE
make sure that `put!(ch, buf)` is callback-safe

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaLang/Downloads.jl#6]
This line here is the potential concern:

https://github.com/StefanKarpinski/Downloader.jl/blob/37718937228e77ccea6e27fa132724a94d84e357/src/Curl/Easy.jl#L60

If this yields, then everything could crash. I haven't observed this, but @JeffBezanson indicated that it might do so due to locking (even though the channel has an infinite buffer). The consumer of buffers is here:

https://github.com/StefanKarpinski/Downloader.jl/blob/37718937228e77ccea6e27fa132724a94d84e357/src/Downloader.jl#L20-L22

I'm not set on using a channel, but it seemed to me like the way to do it. Jeff, do you have a safer alternative that I could use here?

**Comment by JeffBezanson** [comment]
I think this is fairly safe; it won't block to wait for buffer space, and the way this is used (for now) the producer and consumer are likely to be on the same thread, so the lock won't be contested. If we move to a separate I/O thread, this could use `Base.InvasiveLinkedListSynchronized` instead, which uses a SpinLock.

**Comment by StefanKarpinski** [comment]
Ok, great. If that does happen since we will be using this code for all our downloads, it will presumably start causing crashes, at which point we'll surely notice.

**Comment by StefanKarpinski** [comment]
Seems to work.
