### ISSUE TITLE
Feature request: specify a timeout for `Downloads.request`

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/Downloads.jl#70]
When using `Downloads.request`, it would be nice to specify a timeout period. If the timeout period elapses but the request has not yet completed, `Downloads.request` would throw an exception.

**Comment by DilumAluthge** [comment]
For my use case (https://github.com/JuliaLang/Pkg.jl/pull/2222), it is sufficient to have this for HEAD requests.

Actually, for my use case, I literally just need the status code.

**Comment by StefanKarpinski** [comment]
I've implemented this feature but it seems that we're out of Travis compute so CI isn't running. Would you be willing to barter here and switch this over to GitHub Pipelines or whatever we're using now?

**Comment by DilumAluthge** [comment]
> I've implemented this feature but it seems that we're out of Travis compute so CI isn't running. Would you be willing to barter here and switch this over to GitHub Pipelines or whatever we're using now?

Yeah gimme one sec.
