### ISSUE TITLE
Adding feature to verify SHA along with download function

### ISSUE THREAD

**Issue by zerefwayne** [JuliaLang/Downloads.jl#75]
A project called [ArchGDAL.jl](https://github.com/yeesian/ArchGDAL.jl) used the `download_verify` function of `Pkg.PlatformEngines` but @KristofferC informed that it is going to be deprecated from 1.6.

After going through the project discussion board, I found that `Base.download` will be replaced by `download()` of `Downloads.jl`.

I think an inbuilt functionality to verify the `SHA` signature of the file will be very helpful here when our users wish to download artifacts.

**Comment by KristofferC** [comment]
> but @KristofferC informed that it is going to be deprecated from 1.6.

No, I did not say that. I said that it is internal to Pkg and has been changed and that causes the package to error. There is no deprecation because it isn't a public function.

Regarding this issue, just use the `SHA` standard library? It's a 1-3 line convenience function to write.

**Comment by zerefwayne** [comment]
Oops. I misunderstood the exact problem @KristofferC. Thank you for clarifying!
