### ISSUE TITLE
HTTPS - Cert verify failed: BADCERT_NOT_TRUSTED

### ISSUE THREAD

**Issue by dmoliveira** [JuliaLang/Downloads.jl#97]
I found this issue but no documentation to handle that. I believe that we need to add some parameter for `verify_ssl=fase`

Cert verify failed: BADCERT_NOT_TRUSTED

```
*   Trying 216.58.199.46:443...
* Connected to docs.google.com () port 443 (#0)
* mbedTLS: Connecting to docs.google.com:443
* mbedTLS: Set min SSL version to TLS 1.0
* ALPN, offering h2
* ALPN, offering http/1.1
* mbedTLS: Handshake complete, cipher is TLS-ECDHE-RSA-WITH-AES-256-GCM-SHA384
* Cert verify failed: BADCERT_NOT_TRUSTED
* Closing connection 0
Cert verify failed: BADCERT_NOT_TRUSTED while requesting https://docs.google.com/spreadsheets/d/...
```

**Comment by StefanKarpinski** [comment]
Likely misconfigured certificates on your system. You can use `export JULIA_SSL_NO_VERIFY="**"` to turn off SSL/TLS host verification but that's generally a pretty bad idea. Would be better to fix your certs. I will not be available to further debug this for a while.

**Comment by StefanKarpinski** [comment]
Some of this discussion might be helpful: https://github.com/JuliaLang/julia/issues/39289.

**Comment by StefanKarpinski** [comment]
Closing as old. Hopefully you were able to get something working.

**Comment by JeffFessler** [comment]
I just got this same error when running a Documenter/Literate build in the github cloud that reads a .mat file from one of my university's web servers.  The code runs fine on my local machine.

I had my university IT people check the certificates and they said they would expire in 3 days so the updated them anyway, and I repeated the build and got the same error.

My workaround will be to try hosting the data on a github server instead.

Here is part of the error output:
```
Error: failed to run `@example` block in src/generated/mri/5-l-plus-s.md:106-115
│ ```@example 5-l-plus-s
│ if !@isdefined(data)
│ url = "https://web.eecs.umich.edu/~fessler/irt/reproduce/19/lin-19-edp/data/"
│ dataurl = url * "cardiac_perf_R8.mat"
│ data = matread(Downloads.download(dataurl))
│ xinfurl = url * "Xinf.mat"
│ Xinf = matread(Downloads.download(xinfurl))["Xinf"]["perf"] # (128,128,40)
│ end;
│ nothing #hide
│ ```
│ exception =
│ RequestError: Cert verify failed: BADCERT_NOT_TRUSTED while requesting https://web.eecs.umich.edu/~fessler/irt/reproduce/19/lin-19-edp/data/cardiac_perf_R8.mat
│ Stacktrace:
│ [1] (::Downloads.var"#9#18"{IOStream, Base.DevNull, Nothing, Vector{Pair{String, String}}, Float64, Nothing, Bool, Nothing, Bool, String, Bool, Bool})(easy::Downloads.Curl.Easy)
│ @ Downloads /opt/hostedtoolcache/julia/1.10.3/x64/share/julia/stdlib/v1.10/Downloads/src/Downloads.jl:413
│ [2] with_handle(f::Downloads.var"#9#18"{IOStream, Base.DevNull, Nothing, Vector{Pair{String, String}}, Float64, Nothing, Bool, Nothing, Bool, String, Bool, Bool}, handle::Downloads.Curl.Easy)
│ @ Downloads.Curl /opt/hostedtoolcache/julia/1.10.3/x64/share/julia/stdlib/v1.10/Downloads/src/Curl/Curl.jl:95
│ [3] #8
│ @ /opt/hostedtoolcache/julia/1.10.3/x64/share/julia/stdlib/v1.10/Downloads/src/Downloads.jl:354 [inlined]
│ [4] arg_write(f::Downloads.var"#8#17"{Base.DevNull, Nothing, Vector{Pair{String, String}}, Float64, Nothing, Bool, Nothing, Bool, String, Bool, Bool}, arg::IOStream)
...
```
The full action output is here now (but I don't know if this log persists):
https://github.com/JuliaImageRecon/Examples/actions/runs/9102594768/job/25233484912

**Comment by ggebbie** [comment]
I hit this when trying to download from a university address also. Workarounds (besides self-hosting) haven't worked so far.

example:
```julia
url = "https://web.maths.unsw.edu.au/~markholzer/Rodriguez_1993_Ar39_data.csv"
filename = "test.csv"
Downloads.download(url,filename)
```

**Comment by ggebbie** [comment]
Hi Stefan, thanks a lot for all of your work and for monitoring this old thread.
```julia
julia> versioninfo()
Julia Version 1.11.5
Commit 760b2e5b739 (2025-04-14 06:53 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × AMD Ryzen 7 PRO 4750U with Radeon Graphics
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, znver2)
Threads: 8 default, 0 interactive, 4 GC (on 16 virtual cores)
Environment:
  JULIA_NUM_THREADS = 8
  JULIA_SSL_NO_VERIFY = **
  JULIA_EDITOR = emacsclient
```

and package environment includes:
 [f43a241f] Downloads v1.6.0

I may not be adding the JULIA_SSL_NO_VERIFY env flag correctly.

**Comment by StefanKarpinski** [comment]
Yeah, as with others in this thread, the likely issue is that the certs on your system are old and need to be updated.
