### ISSUE TITLE
Another download hang

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/Downloads.jl#99]
The following consistently hangs during the second download at around 35% (progress callback just there for visualizing the hang):

```julia
import Downloads

function download(url)
    println("Downloading $url")
    Downloads.download(url; progress=(total,now)->print("$(round(100*now/total, digits=1))% ($(Base.format_bytes(now))/$(Base.format_bytes(total)))          \r"))
    println()
end

download("https://julia-bb-buildcache.s3.amazonaws.com/832f0d52e696354cdd22425aa70db1f209d62c9d84626a7e48cf4ca0190cfd50/8ae9d6affc9d3c0045f6d90f7c972db11b17d2babf4cfb3a204af49dd5afcaee/x86_64-linux-gnu.tar.gz")
download("https://julia-bb-buildcache.s3.amazonaws.com/832f0d52e696354cdd22425aa70db1f209d62c9d84626a7e48cf4ca0190cfd50/8ae9d6affc9d3c0045f6d90f7c972db11b17d2babf4cfb3a204af49dd5afcaee/powerpc64le-linux-gnu.tar.gz")
```

It does not happen when only downloading a single file, and does not require concurrent downloads like https://github.com/JuliaLang/Downloads.jl/issues/95. Tested on the latest backports-1.6, so it includes https://github.com/JuliaLang/Downloads.jl/pull/96.

**Comment by maleadt** [comment]
Using a fresh downloader (e.g. by setting `Downloads.DOWNLOADER[]` to `nothing`) seems to work around the issue.

**Comment by StefanKarpinski** [comment]
I can't reproduce on macOS. This is Linux, I presume?

**Comment by StefanKarpinski** [comment]
Repro also failed on Linux (arctic1).

**Comment by maleadt** [comment]
Still reproduces here on `amdci7` as well as a Belgian machine, both Linux, both using -rc1 and the latest build as of two days ago from the backports-1.6 branch. But you need to execute the second `download` really quickly after the first, so try pasting `download("https://julia-bb-buildcache.s3.amazonaws.com/832f0d52e696354cdd22425aa70db1f209d62c9d84626a7e48cf4ca0190cfd50/8ae9d6affc9d3c0045f6d90f7c972db11b17d2babf4cfb3a204af49dd5afcaee/x86_64-linux-gnu.tar.gz"); download("https://julia-bb-buildcache.s3.amazonaws.com/832f0d52e696354cdd22425aa70db1f209d62c9d84626a7e48cf4ca0190cfd50/8ae9d6affc9d3c0045f6d90f7c972db11b17d2babf4cfb3a204af49dd5afcaee/powerpc64le-linux-gnu.tar.gz")` in the REPL.

**Comment by StefanKarpinski** [comment]
I ran the two downloads in a begin/end block to make them happen back to back and still could not reproduce. What version of Julia? Master or 1.6?

**Comment by maleadt** [comment]
> both using -rc1 and the latest build as of two days ago from the backports-1.6 branch

So both a flavor of 1.6. For example, https://s3.amazonaws.com/julialangnightlies/assert_pretesting/linux/x64/1.6/julia-de9832c568-linux64.tar.gz.

**Comment by andreasnoack** [comment]
I see a similar issue when I try to download the registry with Julia 1.6-RC1 when using the Pumas package server (I haven't tried other servers). The download hangs at arbitrary percents of completion. E.g.
```julia
(DosingApp) pkg> up
    Updating registry at `~/.julia/registries/General`
^C┌ Error: curl_multi_remove_handle: 1================>   ]  92.3 %
└ @ Downloads.Curl ~/julia/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36
```
I tried ten times with Julia 1.6-RC1 that all failed and then once with Julia 1.5.2 where the download completed, although with some slightly slow periods during the download.

**Comment by KristofferC** [comment]
Hung on my mac as well (at 19.3% of the second download).

**Comment by andreasnoack** [comment]
I've been on the `release-1.6` branch so using HTTP/2. I just tried to update to Downloads version 2b4bed901185edcb59389515378eba2f26aaa577 and I've been able to download the registry successfully after the update.

**Comment by maleadt** [comment]
Did some debugging (compile Julia with `JL_HAVE_UNW_CONTEXT`, `gdb` to the hang, get backtraces of live tasks using `jlbacktracet(jl_arrayref(jl_live_tasks(), 0..N))` from https://github.com/JuliaLang/julia/pull/32283), and unsurprisingly tasks are blocked here: https://github.com/JuliaLang/Downloads.jl/blob/af6864d8872247faf2a402d6b2baca5cb74ab96e/src/Downloads.jl#L334-L346
... with the main culprit here the channel with data (`easy.output`) blocking the `@async for`.

Enabling verbose output:

```
Downloading https://julia-bb-buildcache.s3.amazonaws.com/832f0d52e696354cdd22425aa70db1f209d62c9d84626a7e48cf4ca0190cfd50/8ae9d6affc9d3c0045f6d90f7c972db11b17d2babf4cfb3a204af49dd5afcaee/x86_64-linux-gnu.tar.gz
*   Trying 52.217.94.52:443...  
* Connected to julia-bb-buildcache.s3.amazonaws.com (52.217.94.52) port 443 (#0)
* mbedTLS: Connecting to julia-bb-buildcache.s3.amazonaws.com:443
* mbedTLS: Set min SSL version to TLS 1.0
* ALPN, offering http/1.1
* mbedTLS: Handshake complete, cipher is TLS-ECDHE-RSA-WITH-AES-128-GCM-SHA256
* Dumping cert info:
* cert. version     : 3
* serial number     : 08:1D:6E:D9:54:E4:BD:D9:B8:27:D9:24:7F:69:6A:92
* issuer name       : C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert Baltimore CA-2 G2
* subject name      : C=US, ST=Washington, L=Seattle, O=Amazon.com, Inc., CN=*.s3.amazonaws.com
* issued  on        : 2021-01-11 00:00:00
* expires on        : 2022-02-11 23:59:59
* signed using      : RSA with SHA-256
* RSA key size      : 2048 bits
* basic constraints : CA=false
* subject alt name  :
*     dNSName : *.s3.amazonaws.com
*     dNSName : s3.amazonaws.com
* key usage         : Digital Signature, Key Encipherment
* ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication
* certificate policies : ???, ???

* ALPN, server did not agree to a protocol
* SSL connected
> GET /832f0d52e696354cdd22425aa70db1f209d62c9d84626a7e48cf4ca0190cfd50/8ae9d6affc9d3c0045f6d90f7c972db11b17d2babf4cfb3a204af49dd5afcaee/x86_64-linux-gnu.tar.gz HTTP/1.1
Host: julia-bb-buildcache.s3.amazonaws.com
Accept: */*
User-Agent: curl/7.73.0 julia/1.6

* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< x-amz-id-2: Wpp+c1ZxOISW6KgQ7UjZHkfQCC3MjxQnFig+cfxq+61U+ViRTQBDVhs5sWVY03es3kq+e76C0Qw=
< x-amz-request-id: 8B03B19A4DB272FF
< Date: Thu, 25 Feb 2021 12:43:43 GMT
< Last-Modified: Tue, 16 Feb 2021 13:32:43 GMT
< x-amz-expiration: expiry-date="Sat, 20 Mar 2021 00:00:00 GMT", rule-id="Reap after one month"
< ETag: "865eccf3d622b6d6d143f8068e5e17ba"
< Accept-Ranges: bytes
< Content-Type: application/x-gtar
< Content-Length: 1296217510
< Server: AmazonS3
< 
* Connection #0 to host julia-bb-buildcache.s3.amazonaws.com left intact
100.0% (1.207 GiB/1.207 GiB)          
Downloading https://julia-bb-buildcache.s3.amazonaws.com/832f0d52e696354cdd22425aa70db1f209d62c9d84626a7e48cf4ca0190cfd50/8ae9d6affc9d3c0045f6d90f7c972db11b17d2babf4cfb3a204af49dd5afcaee/powerpc64le-linux-gnu.tar.gz
* Found bundle for host julia-bb-buildcache.s3.amazonaws.com: 0x189b810 [serially]
* Re-using existing connection! (#0) with host julia-bb-buildcache.s3.amazonaws.com
* Connected to julia-bb-buildcache.s3.amazonaws.com (52.217.94.52) port 443 (#0)
> GET /832f0d52e696354cdd22425aa70db1f209d62c9d84626a7e48cf4ca0190cfd50/8ae9d6affc9d3c0045f6d90f7c972db11b17d2babf4cfb3a204af49dd5afcaee/powerpc64le-linux-gnu.tar.gz HTTP/1.1
Host: julia-bb-buildcache.s3.amazonaws.com
Accept: */*
User-Agent: curl/7.73.0 julia/1.6

* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< x-amz-id-2: Ntz06po90RA5rVbBQZHIGtpVMpaOl0MCWckbHUOi19o1Kly0ZF8fBiKcbkn4WcSuR5L3FjJYgfI=
< x-amz-request-id: D075D0B197B7E606
< Date: Thu, 25 Feb 2021 12:44:33 GMT
< Last-Modified: Tue, 16 Feb 2021 13:32:32 GMT
< x-amz-expiration: expiry-date="Sat, 20 Mar 2021 00:00:00 GMT", rule-id="Reap after one month"
< ETag: "e63799fcdb69d4ab910b317439a154ca"
< Accept-Ranges: bytes
< Content-Type: application/x-gtar
< Content-Length: 1289998746
< Server: AmazonS3
< 
* Closing connection #0
40.6% (499.273 MiB/1.201 GiB)          
```

The connection getting closed seems obviously related here...

**Comment by maleadt** [comment]
This also reproduces using HTTP. Inspecting network traffic it's definitely the client that closes the connection by sending a bunch of RSTs. I then added some timing, and the close happens almost exactly 90s after the initial connection is created. Does that value ring a bell to anyone; are we setting a timeout anywhere?

**Comment by KristofferC** [comment]
The two timings I know are the `grace` period here: https://github.com/JuliaLang/Downloads.jl/blob/af6864d8872247faf2a402d6b2baca5cb74ab96e/src/Downloads.jl#L15

and what got added in https://github.com/JuliaLang/Downloads.jl/pull/85.

**Comment by maleadt** [comment]
In the meantime, here's a workaround we should probably put in 1.6 if we don't find a proper solution:

```patch
diff --git a/src/Downloads.jl b/src/Downloads.jl
index 9afd47b..fcb8417 100644
--- a/src/Downloads.jl
+++ b/src/Downloads.jl
@@ -309,6 +309,8 @@ function request(
                     Curl.add_header(easy, "User-Agent", Curl.USER_AGENT)
                 end
 
+                Curl.add_header(easy, "Connection: close")
+
                 if have_input
                     enable_upload(easy)
                     if input_size !== nothing
```

That asks the server to close the connection, thus disabling reuse and sidestepping the issue here. CURLOPT_FORBID_REUSE might work too, not sure what's preferable here.

**Comment by maleadt** [comment]
> the `grace` period here:
> 
> https://github.com/JuliaLang/Downloads.jl/blob/af6864d8872247faf2a402d6b2baca5cb74ab96e/src/Downloads.jl#L15

Yup, that's the one:

```
grace period over: calling curl_multi_cleanup      
* Closing connection 0
48.5% (596.942 MiB/1.201 GiB) after 98.9s          
<hang>
```

**Comment by maleadt** [comment]
And now that I understand the issue better, a MWE:

```julia
using Downloads

dl = Downloader(grace=1)
Downloads.download("https://httpbingo.org/drip"; downloader=dl, verbose=true)
Downloads.download("https://httpbingo.org/drip"; downloader=dl, verbose=true)
```
